development: &development
  adapter: postgresql
  encoding: unicode
  database: test_app_development
  host: localhost
  pool: 5
  username: idt_web
  password:

test:
  <<: *development
  host: postgres
  username: postgres
  database: test_app_test
